Repository Musiverse2024/Musiverse, pull requests merged in 2024-10, with the labels that each got.

#48 se agrega BDD y consultas sql
  Evidencia2/consultas.sql
  Evidencia2/musiverse.sql
Labels: BDD

#49 Busqueda de usuarios por user name o mail
  App/main.py
  Evidencia2/App/usuarios.py
Labels: Python

#50 arreglos de menu
  App/main.py
  Evidencia2/App/main.py
  Evidencia2/App/usuarios.py
  usuarios.ispc
Labels: Python

#51 modificacion de eliminacion de usuario y validacion.
  Evidencia2/App/main.py
  Evidencia2/App/usuarios.py
  Evidencia2/BD Simple Musiverse/BD Musiverse E2.docx
  Evidencia2/BD Simple Musiverse/EERmusiverseE2.mwb
  Evidencia2/BD Simple Musiverse/EERmusiverseE2.mwb.bak
  Evidencia2/BD Simple Musiverse/Musiverse2024.mwb.bak
  Evidencia2/BD Simple Musiverse/MusiverseBDE2.sql
  usuarios.ispc
Labels: Python

#55 Se agrega conexion a BDD
  Evidencia3/app/utils/__pycache__/config.cpython-312.pyc
  Evidencia3/app/utils/__pycache__/db_utils.cpython-312.pyc
  Evidencia3/app/utils/config.py
  Evidencia3/app/utils/db_utils.py
Labels: Python, BDD

#56 Servicio para gestionar el proyecto: album,artistas,etc
  Evidencia3/app/services/__pycache__/album_service.cpython-310.pyc
  Evidencia3/app/services/__pycache__/album_service.cpython-312.pyc
  Evidencia3/app/services/__pycache__/artist_service.cpython-310.pyc
  Evidencia3/app/services/__pycache__/artist_service.cpython-312.pyc
  Evidencia3/app/services/__pycache__/pluvial_service.cpython-310.pyc
  Evidencia3/app/services/__pycache__/pluvial_service.cpython-312.pyc
  Evidencia3/app/services/__pycache__/song_service.cpython-310.pyc
  Evidencia3/app/services/__pycache__/song_service.cpython-312.pyc
  Evidencia3/app/services/__pycache__/user_service.cpython-310.pyc
  Evidencia3/app/services/__pycache__/user_service.cpython-312.pyc
  Evidencia3/app/services/album_service.py
  Evidencia3/app/services/artist_service.py
  Evidencia3/app/services/pluvial_service.py
  Evidencia3/app/services/song_service.py
  Evidencia3/app/services/user_service.py
Labels: Python
